### ISSUE TITLE
Can't compile on builder with other heyzap plugins

### ISSUE THREAD

**Issue by eyalish** [Heyzap/heyzap-cordova-admob#1]
Everything is okay when using two plugins.
when I add the third one, it doesn't compile.
CLI-7.1.0, Android

        <gap:plugin name="heyzap-cordova-admob" spec="https://yyy:xxx@bitbucket.org/eyalish/heyzap-cordova-admob#master" />
        <gap:plugin name="heyzap-cordova-plugin" spec="https://yyy:xxx@bitbucket.org/eyalish/heyzap-cordova-plugin#master"/>
        <gap:plugin name="heyzap-cordova-facebook_audience_network" source="npm" spec="2.0.0"/> 

also, Multidex plugin is running.
the compilation doesn't work? Any Solution?
@ekilah

**Comment by ekilah** [comment]
I'm sorry @eyalish I am no longer a maintainer of this library. please reach out to Heyzap's support.

**Comment by eyalish** [comment]
> 
> 
> I'm sorry @eyalish I am no longer a maintainer of this library. please reach out to Heyzap's support.

Ok. by the way do you know why their email address is no longer alive? 
support@heyzap.com

**Comment by eyalish** [comment]
Issue solved, a day after the post, it was something i can't explain.
